### ISSUE TITLE
Change assertion expiry date?

### ISSUE THREAD

**Issue by johakoch** [kristophjunge/docker-test-saml-idp#28]
Hi,

I would like to change the assertion expiry date created by the IdP. The value of `saml:Assertion/saml:Conditions/@NotOnOrAfter` is currently about 5 minutes in the future. Is there a way to achieve this?

**Comment by cuongluu8** [comment]
I had a similar request.  I ended up overriding the config.php file
```
./saml-config.php:/var/www/simplesamlphp/config/config.php
```
Then in the config there is a `session.duration` property which I changed.

**Comment by johakoch** [comment]
I don't think `session.duration` is the property to change. Its value is
```
8 * (60 * 60), // 8 hours.
```
not 5 minutes.

**Comment by johakoch** [comment]
I could modify the assertion expiry date (`@NotOnOrAfter`) by setting

```php
'assertion.lifetime' => 3600,
```
in metadata/saml20-sp-remote.php.

However, I'm not sure whether this works with the version of simplesamlphp currently used in docker-test-saml-idp, because I updated it to 1.19.0 previously.
