### ISSUE TITLE
Update default SIMPLESAMLPHP_VERSION to 1.14.14

### ISSUE THREAD

**Issue by web-bert** [kristophjunge/docker-test-saml-idp#3]
Also consider making git tags of the versions in between and creating docker tags so others can download a specific version if required?

**Comment by kristophjunge** [comment]
Sorry for the long response time.
- I have updated to SimpleSAMLphp 1.14.15. I hope the intermediate versions are not needed.
- Iam now creating GIT tags for every version
- Iam now creating a branch for each SimpleSAMLphp version starting from 1.14.15 which results in an appropriate docker tag

Thanks for your feedback.

**Comment by web-bert** [comment]
👍
